apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      flaskapp: web
  template:
    metadata:
      labels:
        flaskapp: web
    spec:
      containers:
      - name: flaskapp
        image: sqweeks0p/flask_app:latest
---
apiVersion: v1
kind: Service
metadata:
  name: flask1-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    flaskapp: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30002

